{% set version = "0.1.8" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ggfun
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggfun_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggfun/ggfun_{{ version }}.tar.gz
  sha256: 083f9e668c8d9d24901a41fc8b9e7288b4f21189681783470c909e6958b63f5c

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-dplyr
    - r-ggplot2
    - r-rlang
    - r-yulab.utils >=0.1.6
  run:
    - r-base
    - r-cli
    - r-dplyr
    - r-ggplot2
    - r-rlang
    - r-yulab.utils >=0.1.6

test:
  commands:
    - $R -e "library('ggfun')"           # [not win]
    - "\"%R%\" -e \"library('ggfun')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ggfun
  license: Artistic-2.0
  summary: Useful functions to edit 'ggplot' object (e.g., setting fonts for theme and layers, adding rounded rectangle as background for each of the legends).
  license_family: OTHER
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/Artistic-2.0

extra:
  recipe-maintainers:
    - conda-forge/r
